### ISSUE TITLE
cannot run main.py in paddle project

### ISSUE THREAD

**Issue by sulebaynes** [ZhaoJ9014/face.evoLVe#175]
Hi, 

when trying to run the main.py, I am getting the following error:

```
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    test = FaceEval()
  File "main.py", line 13, in __init__
    self.mtcnn = MTCNN()
  File "/../face.evoLVe.PyTorch/paddle/PaddleInference-demo/utils.py", line 23, in __init__
    self.pnet = init_predictor('../model/PNet')
  File "/../face_recognition/face.evoLVe.PyTorch/paddle/PaddleInference-demo/utils.py", line 17, in init_predictor
    predictor = inference.create_predictor(config)
RuntimeError: (NotFound) Cannot open file ../model/PNet.pdmodel, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at /paddle/paddle/fluid/inference/api/analysis_predictor.cc:915)
```

anyone having the same issue?
thanks in advance

**Comment by alex-xia-xia** [comment]
did you fix that, i got the same problem
